name: Update status

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/10 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring,curl,json
    - name: Run scripts
      env:
        VK_TOKEN: ${{ secrets.VK_TOKEN }}
      run: |
        chmod +x ci-build.sh
        ./ci-build.sh
